# 1. 아주 간단한 버전의 MLP

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
x=iris.data
y = keras.utils.to_categorical(iris.target, 3)


In [ ]:
model = Sequential()
model.add(Dense(4, activation='relu', input_shape=(4,)))
model.add(Dense(3, activation='softmax'))
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


In [ ]:
model.fit(x, y,
          batch_size=10,
          epochs=100,
          verbose=0
)

score = model.evaluate(x, y, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


Test loss: 0.5388548374176025
Test accuracy: 0.8866666555404663


In [ ]:
x[:1,:],y[:1,:],x[60:61,:],y[60:61,:]

(array([[5.1, 3.5, 1.4, 0.2]]),
 array([[1., 0., 0.]], dtype=float32),
 array([[5. , 2. , 3.5, 1. ]]),
 array([[0., 1., 0.]], dtype=float32))

In [ ]:
x_test=np.array( [ [5.1, 3.5, 1.4, 0.2],[5. , 2. , 3.5, 1. ]])
r=model.predict(x_test)
np.argmax(r, axis=-1)

array([0, 1])

# 0,1은 우리가 원하는 답이 아님(Decoding이 되어 있지 않음.)