# 6. RNN



### Recurrent Neural Networks
RNN은 자기자신을 향하는 weight를 이용해 데이터간의 시간관계를 학습할 수 있다. 이러한 문제들을 시계열 학습이라고 부르며, 기존에 널리 쓰이던 Hidden Markov Model을 뉴럴넷을 이용해 구현했다고 볼 수 있다.



## 필요 라이브러리

In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM
 

## 데이터 예시 세팅
x　　y<br>
123　4<br>
234　5<br>
345　6<br>
456　7<br>
다음 수를 예측할 수 있는 모델을 목표로 하는 데이터 세팅

In [2]:
x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6], [5,6,7]])
y = array([4,5,6,7,8])

print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)


x shape :  (5, 3)
y shape :  (5,)


RNN 모델에 맞게 Reshape

In [3]:
x = x.reshape((x.shape[0], x.shape[1], 1)) # (4,3,1) reshape 전체 곱 수 같아야 4*3=4*3*1
print('x shape : ', x.shape)
print(x)

x shape :  (5, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]

 [[5]
  [6]
  [7]]]


## 모델 구성

In [4]:
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(3,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))
 
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10)                480       
_________________________________________________________________
dense (Dense)                (None, 5)                 55        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6         
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


## 모델 학습 시키기

In [5]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)
 

Epoch 1/100
5/5 [==============================] - 19s 5ms/step - loss: 57.6356
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 45.4685
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 37.9281
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 57.0165
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 38.2809
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 39.3277
Epoch 7/100
5/5 [==============================] - 0s 5ms/step - loss: 56.0482
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 54.7432
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 49.9986
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 31.6676
Epoch 11/100
5/5 [==============================] - 0s 4ms/step - loss: 32.9129
Epoch 12/100
5/5 [==============================] - 0s 5ms/step - loss: 33.4844
Epoch 13/100
5/5 [==============================

## TEST

In [6]:

x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)


[[9.514655]]


출처: https://ebbnflow.tistory.com/135 [Dev Log : 삶은 확률의 구름]